# Generated by Django 5.2.6 on 2025-09-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='numero',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='numero',
            name='numero',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
