# Generated by Django 5.2.6 on 2025-09-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa_app', '0002_numero_banco_alter_numero_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='numero',
            name='fecha_compra',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
