# Generated by Django 5.2.6 on 2025-10-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa_app', '0003_numero_fecha_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='numero',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
