# Generated by Django 5.2.6 on 2025-10-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa_app', '0004_numero_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de la Rifa')),
                ('descripcion_corta', models.TextField(verbose_name='Descripción Breve')),
                ('premio_principal', models.CharField(max_length=255, verbose_name='Premio Principal')),
                ('imagen_principal', models.ImageField(upload_to='rifas/', verbose_name='Imagen del Premio')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Costo del Boleto ($)')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_sorteo', models.DateTimeField(verbose_name='Fecha y Hora del Sorteo')),
                ('activa', models.BooleanField(default=True, verbose_name='Rifa Activa')),
            ],
            options={
                'verbose_name': 'Rifa',
                'verbose_name_plural': 'Rifas',
            },
        ),
    ]
