# Generated by Django 5.2.6 on 2025-10-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa_app', '0005_rifa'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifa',
            name='cantidad_numeros',
            field=models.IntegerField(default=10000, help_text='Número total de boletos disponibles (ej: 100 para 00-99, 1000 para 000-999)', verbose_name='Cantidad Total de Números'),
        ),
    ]
