# Generated by Django 5.2.6 on 2025-10-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rifa_app', '0006_rifa_cantidad_numeros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rifa',
            options={},
        ),
    ]
