# Generated by Django 5.2.6 on 2025-10-16 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa_app', '0007_alter_rifa_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='numero',
            options={'verbose_name': 'Número de Boleto', 'verbose_name_plural': 'Números de Boletos'},
        ),
        migrations.AlterModelOptions(
            name='rifa',
            options={'verbose_name': 'Rifa', 'verbose_name_plural': 'Rifas'},
        ),
        migrations.AddField(
            model_name='numero',
            name='rifa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='numeros', to='rifa_app.rifa'),
        ),
        migrations.AlterField(
            model_name='numero',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('vendido', 'Vendido')], default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='numero',
            name='numero',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterUniqueTogether(
            name='numero',
            unique_together={('rifa', 'numero')},
        ),
    ]
