# Generated by Django 5.2.6 on 2025-10-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rifa_app', '0008_alter_numero_options_alter_rifa_options_numero_rifa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifa',
            name='numero_ganador',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número Ganador del Sorteo'),
        ),
    ]
